# The URL the site will be built for
base_url = "https://joss-rendall.github.io/pma-valence/"
title = "Les Petits Marchands Allumés"
description = "Boutique 100% Ğ1"
author = "JossRendall"
theme = "andromeda-theme"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
header_links = [
    {name = "Zola", url = "https://www.getzola.org/"},
    {name = "Blog", url = "https://andromeda-theme.netlify.app"}
]
license = "CC BY-NC 2.0"
email = "joss.rendall@gmail.com"
name = "Joss Rendall"
# favicon = "/images/favicon.ico"

